import { config } from 'dotenv';
config({ path: '.env.local' });

import { db } from '../db';
import { artists, albums, tracks } from '../db/schema';
import { eq } from 'drizzle-orm';

const PIERRE_AKENDENGUE_BIO = `Pierre-Claver Akendengué, né le 25 avril 1942 à Awuta (Gabon), est un chanteur, musicien et poète gabonais. Il a fait ses études en France.`;

const PIERRE_AKENDENGUE_DISCOGRAPHY = [
  {
    title: "Nandipo",
    year: 1974,
    slug: 'nandipo',
    format: "CD",
    label: "Pickled Egg Records (EGG 62)",
    genre: "Electronic / Pop",
    description: "Recorded inside Oslo House and The Speaker Palace, London, in 2004 and 2005.",
    credits: 'Artwork : Chris Irish (2) · Engineer : Hugo Danino · Lyrics By : Justin Paton · Music By : Now (9) · Performer : Angela Last',
    tracks: [
      { title: "Abominatrx", track_number: 1, youtube_url: 'https://www.youtube.com/watch?v=RInHA6pQJrY' },
      { title: "Excited Lobo Crown", track_number: 2, youtube_url: 'https://www.youtube.com/watch?v=m-F_SkKIZYM' },
      { title: "Little Bits Inside Of You", track_number: 3, youtube_url: 'https://www.youtube.com/watch?v=L9VmL-3CDXQ' },
      { title: "The In-Case", track_number: 4, youtube_url: 'https://www.youtube.com/watch?v=L9VmL-3CDXQ' },
      { title: "Will They Come Untamed?", track_number: 5, youtube_url: 'https://www.youtube.com/watch?v=x0jOQw-iT_g' },
      { title: "Container Theory", track_number: 6, youtube_url: 'https://www.youtube.com/watch?v=GF2MH1Jsly8' },
      { title: "Moment", track_number: 7, youtube_url: 'https://www.youtube.com/watch?v=L9VmL-3CDXQ' },
      { title: "By Getting", track_number: 8, youtube_url: 'https://www.youtube.com/watch?v=5Mi2f5k2rZg' },
      { title: "Ne? Un!", track_number: 9, youtube_url: 'https://www.youtube.com/watch?v=PUQMZAvhacQ' },
      { title: "Ra", track_number: 10, youtube_url: 'https://www.youtube.com/watch?v=L9VmL-3CDXQ' },
      { title: "Pachinko", track_number: 11, youtube_url: 'https://www.youtube.com/watch?v=0b332fAlZhM' },
      { title: "Oil On Yr Head", track_number: 12, youtube_url: 'https://www.youtube.com/watch?v=n2DBatm9pt8' },
      { title: "Forage", track_number: 13, youtube_url: 'https://www.youtube.com/watch?v=rsUVGQjXaxw' },
      { title: "Calanized", track_number: 14, youtube_url: 'https://www.youtube.com/watch?v=0b332fAlZhM' },
      { title: "I Heard Footsteps Outside, Soft Footsteps... Like Naked Feet", track_number: 15, youtube_url: 'https://www.youtube.com/watch?v=tmOXwYegGLQ' },
      { title: "Grotesque And Cute", track_number: 16, youtube_url: 'https://www.youtube.com/watch?v=n2DBatm9pt8' },
      { title: "Lobo Crown", track_number: 17, youtube_url: 'https://www.youtube.com/watch?v=cR7Dyov30po' },
    ],
  },
  {
    title: "Likwala",
    year: 1975,
    slug: 'likwala',
    format: "Vinyl",
    label: "Saravah (SH 40058)",
    genre: "Funk / Soul / African",
    description: "",
    credits: 'Accompanied By : Orchestre Zakuna · Chorus : Angèle Ntchewe · Drums, Vocals : François Ombanda · Engineer : Christian Gence · Engineer [Assistant] : Pascal Belaud · Flute : Jean-Claude Dequéant · Lead Guitar [Solo], Organ, Percussion : Charles Edjiwet · Photography By : Robert Destanque',
    tracks: [
      { title: "Likwala", track_number: 1, youtube_url: 'https://www.youtube.com/watch?v=4KcW1-G7qBk' },
      { title: "Tonda", track_number: 2, youtube_url: 'https://www.youtube.com/watch?v=5Mi2f5k2rZg' },
    ],
  },
  {
    title: "Afrika Obota",
    year: 1976,
    slug: 'afrika-obota',
    format: "Vinyl",
    label: "Record Shack Records (RSR001)",
    genre: "Electronic / Hi NRG",
    description: "Cover medley of Madonna songs: Frozen, Like A Virgin, Don't Cry For Me Argentina, Vogue, Open Your Heart, Frozen",
    credits: null,
    tracks: [],
  },
  {
    title: "Owende",
    year: 1978,
    slug: 'owende',
    format: "Vinyl",
    label: "Le Chant Du Monde (LDX 74677)",
    genre: "Folk, World, & Country / African",
    description: "Gatefold sleeve, liner notes in French, lyrics in Gabonese with French translation, and in original French where applicable\nSpine: LDX 74677 – Pierre Akkendengue/Owende/Le Chant Du Monde\n \n—Center labels info—\n- 09 -\n℗ 1978\nMade In France\nStéréo compatible\n—\nCatalog#: LDX 74 677",
    credits: 'Arranged By, Chorus Master [Arrangements Et Direction Des Chœurs] : Pierre Akendengue · Balafon, Percussion, Voice : Prosper N\'Kouri · Chorus [Chœurs] : Françoise Ngwanga · Contrabass : Didier Levallet · Design, Layout [Maquette Et Mise En Page] : Anne-Marie Dufour · Flute : Denis Barbier · Guitar : Francisco Timoteo · Keyboards, Directed By [Directeur Des Séances] : Michel Carras',
    tracks: [
      { title: "Nthi 'oba", track_number: 1, youtube_url: 'https://www.youtube.com/watch?v=SMcoaChp69A' },
      { title: "Battez Des Mains (Chant Pour Guitare, Tam-tam Ou Ingidi)", track_number: 2, youtube_url: 'https://www.youtube.com/watch?v=4jBpvceTQVw' },
      { title: "Osoto", track_number: 3, youtube_url: 'https://www.youtube.com/watch?v=UkhBsAVFm8E' },
      { title: "Anome Anomie", track_number: 4, youtube_url: 'https://www.youtube.com/watch?v=gY-BzxsCeHg' },
      { title: "Bineng", track_number: 5, youtube_url: 'https://www.youtube.com/watch?v=Jo5n0vn-M4E' },
      { title: "My' Be Kalwa", track_number: 6, youtube_url: 'https://www.youtube.com/watch?v=-HTsmRylsbI' },
      { title: "Apolongo", track_number: 7, youtube_url: 'https://www.youtube.com/watch?v=c25PqcPe8ZQ' },
      { title: "Intyayi S'arende", track_number: 8, youtube_url: 'https://www.youtube.com/watch?v=m-F_SkKIZYM' },
      { title: "Owende", track_number: 9, youtube_url: 'https://www.youtube.com/watch?v=4jyGrFzfaTE' },
    ],
  },
  {
    title: "Ntin'Oba / Bineng",
    year: 1978,
    slug: 'ntin-oba-bineng',
    format: "Vinyl",
    label: "Le Chant Du Monde (45-1248)",
    genre: "Folk, World, & Country / African",
    description: "",
    credits: null,
    tracks: [
      { title: "Ntin'Oba", track_number: 1, youtube_url: 'https://www.youtube.com/watch?v=SMcoaChp69A' },
      { title: "Bineng", track_number: 2, youtube_url: 'https://www.youtube.com/watch?v=Jo5n0vn-M4E' },
    ],
  },
  {
    title: "Eseringila (Trait D'Union)",
    year: 1978,
    slug: 'eseringila-trait-d-union',
    format: "Vinyl",
    label: "Cooltempo (1C 064-3 21890 1)",
    genre: "Electronic / Funk / Soul",
    description: "Includes a printed inner sleeve with lyrics.\n\nLabels:\nMade in EEC\nDMM\n\nRear sleeve & labels:\n℗ & © 1991 Chrysalis Records Ltd.\n\nRear sleeve:\nProduced by Ian Green for Fnoot Productions.\nExcept 1.1 produced by Richie Fermie and Glen Gunner for Fnoot Productions Ltd. and 2.3 produced by Tim Lever and Mike Percy for One World Productions Ltd.\n\nRunouts are stamped except the \"1\" at the end of variant ",
    credits: 'Design : Wilf (6) · Engineer : John Lyons (3) · Photography By [Photographed By] : Simon Fowler (2) · Producer : Glen Gunner',
    tracks: [
      { title: "Outstanding", track_number: 1, youtube_url: 'https://www.youtube.com/watch?v=5Mi2f5k2rZg' },
      { title: "Best Of You", track_number: 2, youtube_url: 'https://www.youtube.com/watch?v=YtzswwSQh-A' },
      { title: "Tender Love", track_number: 3, youtube_url: 'https://www.youtube.com/watch?v=d6AZs2YVUu0' },
      { title: "Were We Ever In Love?", track_number: 4, youtube_url: 'https://www.youtube.com/watch?v=n2DBatm9pt8' },
      { title: "Something Special", track_number: 5, youtube_url: 'https://www.youtube.com/watch?v=L9VmL-3CDXQ' },
      { title: "If You Believe", track_number: 6, youtube_url: 'https://www.youtube.com/watch?v=L9VmL-3CDXQ' },
      { title: "Will I Ever See Your Face?", track_number: 7, youtube_url: 'https://www.youtube.com/watch?v=GlfmyZas50k' },
      { title: "Thinking About Your Love", track_number: 8, youtube_url: 'https://www.youtube.com/watch?v=g4oChq_l8pA' },
      { title: "Voices", track_number: 9, youtube_url: 'https://www.youtube.com/watch?v=rNQ8Nk4SgGs' },
      { title: "Girlfriend", track_number: 10, youtube_url: 'https://www.youtube.com/watch?v=GE25DrpVL3k' },
      { title: "Will I Ever See Your Face? (Reprise)", track_number: 11, youtube_url: 'https://www.youtube.com/watch?v=d9xmMK-uWLA' },
    ],
  },
  {
    title: "Méngo",
    year: 1980,
    slug: 'mengo',
    format: "Vinyl",
    label: "NTYE (NT/AKN 13002)",
    genre: "Folk, World, & Country / African",
    description: "",
    credits: 'Backing Vocals : Liliane Mayordome · Backing Vocals, Layout : Marianne Ndjongue · Bass : Aladji Touré · Cavaquinho : Chiquinho Timotéo · Drawing : F. Benveniste · Drums : Brice Wassy · Flute : Richard Raux · Guitar : Charles Edjiwet',
    tracks: [
      { title: "Méngo", track_number: 1, youtube_url: 'https://www.youtube.com/watch?v=V5orLtrPDd4' },
      { title: "Aux Dieux De Ce Monde", track_number: 2, youtube_url: 'https://www.youtube.com/watch?v=OsuDk1hPWw0' },
      { title: "Nkombe", track_number: 3, youtube_url: 'https://www.youtube.com/watch?v=GF2MH1Jsly8' },
      { title: "Chaka (1786 - 1828)", track_number: 4, youtube_url: 'https://www.youtube.com/watch?v=Fbtt7GgVTm0' },
      { title: "Piamidanga (La Rapporteur)", track_number: 5, youtube_url: 'https://www.youtube.com/watch?v=IKDJDGET4pM' },
      { title: "Kengele", track_number: 6, youtube_url: 'https://www.youtube.com/watch?v=vI4h6Oily1I' },
      { title: "Izingo (Dur - Dur - Dur)", track_number: 7, youtube_url: 'https://www.youtube.com/watch?v=CBq19diUP1o' },
      { title: "Mye We", track_number: 8, youtube_url: 'https://www.youtube.com/watch?v=cK-PpqDt21s' },
      { title: "Ibangani", track_number: 9, youtube_url: 'https://www.youtube.com/watch?v=rbGLfeCzX1I' },
    ],
  },
  {
    title: "Reveil De L'Afrique",
    year: 1980,
    slug: 'reveil-de-l-afrique',
    format: "CD",
    label: "Ubiquity (URCD211)",
    genre: "Electronic / Experimental",
    description: "urcd211 [#Cat Printed on disc]",
    credits: 'Co-producer : Asger Baden · Mastered By : Anders Schumann · Mixed By : Anders Schumann · Producer : Peder',
    tracks: [
      { title: "Ache", track_number: 1, youtube_url: 'https://www.youtube.com/watch?v=L9VmL-3CDXQ' },
      { title: "The Sour", track_number: 2, youtube_url: 'https://www.youtube.com/watch?v=5Mi2f5k2rZg' },
      { title: "Botan", track_number: 3, youtube_url: 'https://www.youtube.com/watch?v=C6QoFjSKbig' },
      { title: "Would You", track_number: 4, youtube_url: 'https://www.youtube.com/watch?v=GlfmyZas50k' },
      { title: "Void", track_number: 5, youtube_url: 'https://www.youtube.com/watch?v=5Mi2f5k2rZg' },
      { title: "Timetakesthetimetimetakes", track_number: 6, youtube_url: 'https://www.youtube.com/watch?v=YtzswwSQh-A' },
      { title: "White Lillies", track_number: 7, youtube_url: 'https://www.youtube.com/watch?v=YtzswwSQh-A' },
      { title: "Ploy Sexy", track_number: 8, youtube_url: 'https://www.youtube.com/watch?v=L9VmL-3CDXQ' },
      { title: "With A Great Feeling Of Love", track_number: 9, youtube_url: 'https://www.youtube.com/watch?v=L9VmL-3CDXQ' },
      { title: "Numb Cinema", track_number: 10, youtube_url: 'https://www.youtube.com/watch?v=L9VmL-3CDXQ' },
      { title: "Klart", track_number: 11, youtube_url: 'https://www.youtube.com/watch?v=5kZb88t7zS0' },
      { title: "Nothing", track_number: 12, youtube_url: 'https://www.youtube.com/watch?v=CBq19diUP1o' },
      { title: "Conserva", track_number: 13, youtube_url: 'https://www.youtube.com/watch?v=-gfdpD4FnYw' },
    ],
  },
  {
    title: "Mando",
    year: 1983,
    slug: 'mando',
    format: "Vinyl",
    label: "Sub Pop (SP 763)",
    genre: "Rock / Stoner Rock",
    description: "© Wooden Shjips\r\n© ℗ 2007 Sub Pop Records\r\n\r\nReleased in a foldover sleeve with plastic bag.",
    credits: 'Artwork : Jeff Kleinsmith · Songwriter, Written By : Wooden Shjips',
    tracks: [
      { title: "Loose Lips", track_number: 1, youtube_url: 'https://www.youtube.com/watch?v=zOzo0ak_vSw' },
      { title: "Start To Dreaming", track_number: 2, youtube_url: 'https://www.youtube.com/watch?v=5Mi2f5k2rZg' },
    ],
  },
  {
    title: "Epuguzu",
    year: 1983,
    slug: 'epuguzu',
    format: "Vinyl",
    label: "Creative Funk (CF-10000)",
    genre: "Hip Hop / Go-Go",
    description: "100 BPM\nRecorded at The Studio and Central Recording",
    credits: 'Engineer [Mixing] : Michael Neal · Mixed By, Written-By : DJ Kool · Producer : DJ Kool',
    tracks: [
      { title: "How Low Can You Go (Radio Edit)", track_number: 1, youtube_url: 'https://www.youtube.com/watch?v=X_D0hLJ0NQU' },
      { title: "How Low Can You Go (Extended)", track_number: 2, youtube_url: 'https://www.youtube.com/watch?v=bepsJLbfFy0' },
    ],
  },
  {
    title: "Awana W'Afrika",
    year: 1983,
    slug: 'awana-w-afrika',
    format: "Cassette",
    label: "Not On Label",
    genre: "Rock / Goth Rock",
    description: "Recorded in November 1991.",
    credits: 'Bass : Jörg Egger · Drums : Dirk Hauer · Guitar : Frank Stelnke · Producer : Phobia (10) · Vocals : Oliver Mann',
    tracks: [
      { title: "Wake Up", track_number: 1, youtube_url: 'https://www.youtube.com/watch?v=__cwIiHJhB0' },
      { title: "Only One Reason", track_number: 2, youtube_url: 'https://www.youtube.com/watch?v=GlfmyZas50k' },
      { title: "Jack Is Back", track_number: 3, youtube_url: 'https://www.youtube.com/watch?v=5Mi2f5k2rZg' },
      { title: "World In Ruins", track_number: 4, youtube_url: 'https://www.youtube.com/watch?v=jvmL9SwCMgE' },
      { title: "Into The Fire", track_number: 5, youtube_url: 'https://www.youtube.com/watch?v=L9VmL-3CDXQ' },
      { title: "Lost My Mind", track_number: 6, youtube_url: 'https://www.youtube.com/watch?v=rNQ8Nk4SgGs' },
      { title: "Morning Mist", track_number: 7, youtube_url: 'https://www.youtube.com/watch?v=5Mi2f5k2rZg' },
      { title: "Susanne Never Knows", track_number: 8, youtube_url: 'https://www.youtube.com/watch?v=5Mi2f5k2rZg' },
      { title: "Age Of Sin", track_number: 9, youtube_url: 'https://www.youtube.com/watch?v=n2DBatm9pt8' },
      { title: "Angel", track_number: 10, youtube_url: 'https://www.youtube.com/watch?v=C6QoFjSKbig' },
      { title: "Rattengift", track_number: 11, youtube_url: 'https://www.youtube.com/watch?v=Ij79HO-L1f4' },
      { title: "*", track_number: 12, youtube_url: 'https://www.youtube.com/watch?v=PUQMZAvhacQ' },
    ],
  },
  {
    title: "Afrika Obota / Nandipo",
    year: 1985,
    slug: 'afrika-obota-nandipo',
    format: "CD",
    label: "DTM (DTM 0500)",
    genre: "Electronic / Trance",
    description: "Distributed by Town Music, 56814 Ernst/Mosel\r\n℗ + © 1993",
    credits: 'Design [Cover Design By] : Double-You-Eleven',
    tracks: [
      { title: "Te Quierro", track_number: 1, youtube_url: 'https://www.youtube.com/watch?v=oyja69LpFAI' },
      { title: "Runnin'", track_number: 2, youtube_url: 'https://www.youtube.com/watch?v=KHhxzJxV-5c' },
      { title: "Koma", track_number: 3, youtube_url: 'https://www.youtube.com/watch?v=_gMkSh5yoAk' },
      { title: "Captain Future", track_number: 4, youtube_url: 'https://www.youtube.com/watch?v=n2DBatm9pt8' },
      { title: "Bladerunner", track_number: 5, youtube_url: 'https://www.youtube.com/watch?v=C6QoFjSKbig' },
      { title: "Confusion", track_number: 6, youtube_url: 'https://www.youtube.com/watch?v=yywzl2MekoA' },
      { title: "Batucada", track_number: 7, youtube_url: 'https://www.youtube.com/watch?v=L9VmL-3CDXQ' },
      { title: "E-Shopping (Ich Möchte Ein 'E' Kaufen)", track_number: 8, youtube_url: 'https://www.youtube.com/watch?v=pyaqABrq8UE' },
      { title: "Homosexual Invasion", track_number: 9, youtube_url: 'https://www.youtube.com/watch?v=qbbA3VyZrgU' },
      { title: "Visions Of Singapore", track_number: 10, youtube_url: 'https://www.youtube.com/watch?v=rgg-2ehL--s' },
      { title: "Father Brown Is Black", track_number: 11, youtube_url: 'https://www.youtube.com/watch?v=GZ5M04wrFCc' },
      { title: "Halloween", track_number: 12, youtube_url: 'https://www.youtube.com/watch?v=9YQzL_zzI3U' },
    ],
  },
  {
    title: "Sarraounia",
    year: 1986,
    slug: 'sarraounia',
    format: "Vinyl",
    label: "Milan (A 295)",
    genre: "Pop / Folk, World, & Country",
    description: "℗ 1986 by SEPAM © 1986",
    credits: 'Arranged By : Philippe Briche · Liner Notes : Christophe d\'Yvoire',
    tracks: [
      { title: "Sarraounia", track_number: 1, youtube_url: 'https://www.youtube.com/watch?v=Wbe6S7dhico' },
      { title: "Iyo", track_number: 2, youtube_url: 'https://www.youtube.com/watch?v=UhzJdJ2S8Z0' },
      { title: "Kia", track_number: 3, youtube_url: 'https://www.youtube.com/watch?v=7YEChRHwJac' },
      { title: "Vivi Li Franci", track_number: 4, youtube_url: 'https://www.youtube.com/watch?v=UbbJhwzDWPI' },
      { title: "Ekewa", track_number: 5, youtube_url: 'https://www.youtube.com/watch?v=rNQ8Nk4SgGs' },
      { title: "Sarraounia (Version Longue)", track_number: 6, youtube_url: 'https://www.youtube.com/watch?v=Wbe6S7dhico' },
      { title: "Iyo (Instrumental)", track_number: 7, youtube_url: 'https://www.youtube.com/watch?v=_GonWnddj-4' },
      { title: "La Marche Du Voulet", track_number: 8, youtube_url: 'https://www.youtube.com/watch?v=vCQQZWKSDxU' },
      { title: "Ahan", track_number: 9, youtube_url: 'https://www.youtube.com/watch?v=L9VmL-3CDXQ' },
      { title: "Sarraounia (Version Flute)", track_number: 10, youtube_url: 'https://www.youtube.com/watch?v=Wbe6S7dhico' },
    ],
  },
  {
    title: "Ka'Bo",
    year: 1986,
    slug: 'ka-bo',
    format: "File",
    label: "Covert Operations Recordings (COVNTD009)",
    genre: "Electronic / Drum n Bass",
    description: "",
    credits: null,
    tracks: [
      { title: "Datura", track_number: 1, youtube_url: 'https://www.youtube.com/watch?v=5Mi2f5k2rZg' },
      { title: "Earthtones", track_number: 2, youtube_url: 'https://www.youtube.com/watch?v=-gfdpD4FnYw' },
    ],
  },
  {
    title: "Passé Composé",
    year: 1987,
    slug: 'passe-compose',
    format: "CD",
    label: "Encore ! (493402)",
    genre: "Folk, World, & Country / African",
    description: "",
    credits: 'Lyrics By : Pierre Akendengue · Music By : Pierre Akendengue · Producer : Michel Carras',
    tracks: [
      { title: "Oma Ayiya", track_number: 1, youtube_url: 'https://www.youtube.com/watch?v=UhzJdJ2S8Z0' },
      { title: "Le Chant Du Coupeur D'Okoume", track_number: 2, youtube_url: 'https://www.youtube.com/watch?v=VqmzSNRzXuY' },
      { title: "Afrika Obota", track_number: 3, youtube_url: 'https://www.youtube.com/watch?v=dBbVvlmYeg8' },
      { title: "Negro", track_number: 4, youtube_url: 'https://www.youtube.com/watch?v=cDk9L72ZkuE' },
      { title: "Considerable", track_number: 5, youtube_url: 'https://www.youtube.com/watch?v=0b332fAlZhM' },
      { title: "Mengo", track_number: 6, youtube_url: 'https://www.youtube.com/watch?v=V5orLtrPDd4' },
      { title: "Ntin Oba", track_number: 7, youtube_url: 'https://www.youtube.com/watch?v=SMcoaChp69A' },
      { title: "Awana W'Afrika", track_number: 8, youtube_url: 'https://www.youtube.com/watch?v=rRjVYZbFDTo' },
      { title: "Salut Aux Combattants De La Liberté", track_number: 9, youtube_url: 'https://www.youtube.com/watch?v=fAi7forphqU' },
      { title: "Piroguier", track_number: 10, youtube_url: 'https://www.youtube.com/watch?v=-UIxRYM1S5U' },
      { title: "Ayile", track_number: 11, youtube_url: 'https://www.youtube.com/watch?v=_u6m7c7yUVQ' },
      { title: "Epuguzu", track_number: 12, youtube_url: 'https://www.youtube.com/watch?v=n6hiP1smKf4' },
      { title: "Okuwa", track_number: 13, youtube_url: 'https://www.youtube.com/watch?v=nxBeXVGR1CE' },
      { title: "Mintele", track_number: 14, youtube_url: 'https://www.youtube.com/watch?v=S_jYgWdSyR4' },
    ],
  },
  {
    title: "Piroguier",
    year: 1987,
    slug: 'piroguier',
    format: "",
    label: "",
    genre: "",
    description: "",
    credits: null,
    tracks: [],
  },
  {
    title: "Espoir A Soweto",
    year: 1988,
    slug: 'espoir-a-soweto',
    format: "Vinyl",
    label: "Einmaleins Musik (EINMALEINS 001)",
    genre: "Electronic / Experimental",
    description: "Manufactured by R.A.N.D. Muzik Record Manufacturing.",
    credits: null,
    tracks: [
      { title: "Naš Fank", track_number: 1, youtube_url: 'https://www.youtube.com/watch?v=SbM738tQsH8' },
      { title: "Freak For Schmeisser", track_number: 2, youtube_url: 'https://www.youtube.com/watch?v=DbSS-1MLkIY' },
      { title: "Kleines Bongo Mädchen", track_number: 3, youtube_url: 'https://www.youtube.com/watch?v=5kZb88t7zS0' },
      { title: "Freak For Live", track_number: 4, youtube_url: 'https://www.youtube.com/watch?v=DbSS-1MLkIY' },
    ],
  },
  {
    title: "Nandipo / Afrika Obota",
    year: 1991,
    slug: 'nandipo-afrika-obota',
    format: "CD",
    label: "Saravah (-591051-)",
    genre: "Jazz / Latin",
    description: "Compilation of two albums.",
    credits: null,
    tracks: [
      { title: "Afrika", track_number: 1, youtube_url: 'https://www.youtube.com/watch?v=dBbVvlmYeg8' },
      { title: "Negro", track_number: 2, youtube_url: 'https://www.youtube.com/watch?v=cDk9L72ZkuE' },
      { title: "Evo", track_number: 3, youtube_url: 'https://www.youtube.com/watch?v=rgg-2ehL--s' },
      { title: "Considerable", track_number: 4, youtube_url: 'https://www.youtube.com/watch?v=0b332fAlZhM' },
      { title: "Orema Ka-Ka-Ka", track_number: 5, youtube_url: 'https://www.youtube.com/watch?v=b08yW-NqR1s' },
      { title: "Orei II", track_number: 6, youtube_url: 'https://www.youtube.com/watch?v=sfnk2UG8T8c' },
      { title: "Sa Gunu, Sa Gunu", track_number: 7, youtube_url: 'https://www.youtube.com/watch?v=QWJaKFs3SZ8' },
      { title: "Mon Pays Entre Soleil Et Pluie", track_number: 8, youtube_url: 'https://www.youtube.com/watch?v=4sWOLzcO1ng' },
      { title: "Olatano, W'intye So Du S'Afrika", track_number: 9, youtube_url: 'https://www.youtube.com/watch?v=AOzDuIyVubM' },
      { title: "Oma Ayiya", track_number: 10, youtube_url: 'https://www.youtube.com/watch?v=UhzJdJ2S8Z0' },
      { title: "Chant Du Coupeur D'Oukoume", track_number: 11, youtube_url: 'https://www.youtube.com/watch?v=VqmzSNRzXuY' },
      { title: "Poe", track_number: 12, youtube_url: 'https://www.youtube.com/watch?v=gA55781ShS8' },
      { title: "Sesi", track_number: 13, youtube_url: 'https://www.youtube.com/watch?v=pcLYeyZdPfE' },
      { title: "Ogowe", track_number: 14, youtube_url: 'https://www.youtube.com/watch?v=UW_InV6C32E' },
      { title: "Le Trottoir D'en Face", track_number: 15, youtube_url: 'https://www.youtube.com/watch?v=fobo4FM2DCI' },
      { title: "Ompung'ilendo", track_number: 16, youtube_url: 'https://www.youtube.com/watch?v=H5ik0CjZVGY' },
      { title: "Onaga Are Mie", track_number: 17, youtube_url: 'https://www.youtube.com/watch?v=uWO1UbsDLHA' },
      { title: "Un Conte Du Roi Orei", track_number: 18, youtube_url: 'https://www.youtube.com/watch?v=N6nXqO7LowM' },
      { title: "Nandipo", track_number: 19, youtube_url: 'https://www.youtube.com/watch?v=UkhBsAVFm8E' },
    ],
  },
  {
    title: "Silence",
    year: 1991,
    slug: 'silence',
    format: "CD",
    label: "Airplay Records (853 777-2)",
    genre: "Electronic / Euro House",
    description: "",
    credits: 'Artwork : Jean-Paul Théodule · Executive-Producer : Claudio Donato · Producer : Fargetta · Producer, Arranged By, Mixed By : Pieradis Rossini',
    tracks: [
      { title: "Gotta Be Good (Radio Edit)", track_number: 1, youtube_url: 'https://www.youtube.com/watch?v=L9VmL-3CDXQ' },
      { title: "Gotta Be Good (Get Far Mix)", track_number: 2, youtube_url: 'https://www.youtube.com/watch?v=UbbJhwzDWPI' },
      { title: "Gotta Be Good (Club Mix)", track_number: 3, youtube_url: 'https://www.youtube.com/watch?v=qbbA3VyZrgU' },
    ],
  },
  {
    title: "Maladalite",
    year: 1996,
    slug: 'maladalite',
    format: "CD",
    label: "Celluloid (66976-2)",
    genre: "Folk, World, & Country / African",
    description: "Standard jewel case, 16-page booklet.\n\nIn rim text: Made in France.",
    credits: 'Contrabass : Linley Marthe · Cover [Graphisme Pochette] : Antoine Castro · Cowbell : Augustin Eyenga · Design Concept [Conception Maquette] : Frédéric Locca · Drums [Tambours d\'Eau], Percussion [Kélé], Wood Block, Congas, Percussion [Nkul], Percussion [Claves] : Augustin Eyenga · Executive-Producer [Production Déléguée], Realization : Hughes de Courson · Guitar : Constantin Ambassa · Maracas : Augustin Eyenga',
    tracks: [
      { title: "Maladalité", track_number: 1, youtube_url: 'https://www.youtube.com/watch?v=r6oCI3phAyM' },
      { title: "Eau Claire", track_number: 2, youtube_url: 'https://www.youtube.com/watch?v=Ex_Z-XwVQ3Q' },
      { title: "Ndyelee", track_number: 3, youtube_url: 'https://www.youtube.com/watch?v=m1FOVLMaJCg' },
      { title: "R'ragnambié", track_number: 4, youtube_url: 'https://www.youtube.com/watch?v=-YTe6nS-QTM' },
      { title: "Y'a Pas Ça Sans Ça", track_number: 5, youtube_url: 'https://www.youtube.com/watch?v=7oo9xHRXZKs' },
      { title: "Ghetaabee", track_number: 6, youtube_url: 'https://www.youtube.com/watch?v=5_zCfR2xrZs' },
      { title: "Gabon Epambia", track_number: 7, youtube_url: 'https://www.youtube.com/watch?v=E_xUVC3dJok' },
      { title: "Akewa", track_number: 8, youtube_url: 'https://www.youtube.com/watch?v=H_pFkJyVK9k' },
      { title: "Eleke", track_number: 9, youtube_url: 'https://www.youtube.com/watch?v=VZ-bIBM_KN8' },
      { title: "Nwo Nwombi", track_number: 10, youtube_url: 'https://www.youtube.com/watch?v=3FtNFCKI2Uw' },
      { title: "Double Distance", track_number: 11, youtube_url: 'https://www.youtube.com/watch?v=mwIl1YtZ4m8' },
      { title: "Ewulupupa", track_number: 12, youtube_url: 'https://www.youtube.com/watch?v=MWslD4ZKrhE' },
    ],
  },
  {
    title: "Carrefour Rio",
    year: 1996,
    slug: 'carrefour-rio',
    format: "CD",
    label: "Mepa Gabon (MEPA 8961)",
    genre: "Folk, World, & Country / African",
    description: "",
    credits: null,
    tracks: [
      { title: "Carrefour Rio", track_number: 1, youtube_url: 'https://www.youtube.com/watch?v=CeZFKwZpXkg' },
      { title: "Toto Méné", track_number: 2, youtube_url: 'https://www.youtube.com/watch?v=d9xmMK-uWLA' },
      { title: "Sans Oublier L`oublié", track_number: 3, youtube_url: 'https://www.youtube.com/watch?v=_gMkSh5yoAk' },
      { title: "Pauvre Okhugué", track_number: 4, youtube_url: 'https://www.youtube.com/watch?v=Tp7goxrBNFs' },
      { title: "Mbéro", track_number: 5, youtube_url: 'https://www.youtube.com/watch?v=C6QoFjSKbig' },
      { title: "Souriez", track_number: 6, youtube_url: 'https://www.youtube.com/watch?v=sGCsSerrOus' },
      { title: "Nomboramba", track_number: 7, youtube_url: 'https://www.youtube.com/watch?v=_GNuTbzM__c' },
      { title: "Soké Soké", track_number: 8, youtube_url: 'https://www.youtube.com/watch?v=6AiA74yE-tE' },
      { title: "Engongona", track_number: 9, youtube_url: 'https://www.youtube.com/watch?v=7YEChRHwJac' },
      { title: "Né O", track_number: 10, youtube_url: 'https://www.youtube.com/watch?v=yywzl2MekoA' },
    ],
  },
  {
    title: "Obakadences",
    year: 2001,
    slug: 'obakadences',
    format: "CD",
    label: "Mélodie Distribution (796362)",
    genre: "Folk, World, & Country / African",
    description: "&#8471 + © Mélodie 2001\r\n\r\nMade in France",
    credits: 'Acoustic Guitar : Jacky Arconte · Acoustic Guitar, Sequenced By : Constantin Ambassa · Arranged By : Nicolas Mingot · Arranged By, Acoustic Guitar : Pierre Akendengue · Arranged By, Bass Guitar, Sequenced By : Ivan Lantos · Arranged By, Keyboards, Sequenced By : François Moity · Arranged By, Sequenced By : Moustick Ambassa · Artwork [Conception Graphique] : Matthieu Junquet',
    tracks: [
      { title: "E.U.A. Ntyire", track_number: 1, youtube_url: 'https://www.youtube.com/watch?v=UFIOxkaVuVA' },
      { title: "Lambaiya", track_number: 2, youtube_url: 'https://www.youtube.com/watch?v=zV9ojBszGIo' },
      { title: "Benibeni", track_number: 3, youtube_url: 'https://www.youtube.com/watch?v=eDGJY6NsQOI' },
      { title: "Wuliewulie", track_number: 4, youtube_url: 'https://www.youtube.com/watch?v=xNzdaVL8KZQ' },
      { title: "Bonne Modernité", track_number: 5, youtube_url: 'https://www.youtube.com/watch?v=VmSsfBgIRBg' },
      { title: "Confidentiel ô Très Haut", track_number: 6, youtube_url: 'https://www.youtube.com/watch?v=upRMs7LoqaA' },
      { title: "Afrika Idod' Iningo", track_number: 7, youtube_url: 'https://www.youtube.com/watch?v=iZ2XnIsiLSU' },
      { title: "Nzambe", track_number: 8, youtube_url: 'https://www.youtube.com/watch?v=vE4pn7K8AFo' },
      { title: "Bimbia Re Deg' Oma Penda", track_number: 9, youtube_url: 'https://www.youtube.com/watch?v=RInHA6pQJrY' },
      { title: "Viyo : Ténèbres", track_number: 10, youtube_url: 'https://www.youtube.com/watch?v=FYG5Lh6-iOY' },
    ],
  },
  {
    title: "Rereleases Of The Albums \"Eseringila\" And \"Mengo\"",
    year: 2002,
    slug: 'rereleases-of-the-albums-eseringila-and-mengo',
    format: "CD",
    label: "Mélodie Distribution (79633.2)",
    genre: "Folk, World, & Country",
    description: "Tracks 1 to 4, 6 & 7 extracts from the album \"Eseringila\".\r\nTracks 8 to 15 extracts from the album \"Méngo\"\r\n\r\n℗ 1978, 1980 NTYE\r\n© 2002 Mélodie",
    credits: 'Accordion : Michel Carras · Acoustic Guitar, Arranged By, Directed By [Choir], Vocals : Pierre Akendengue · Acoustic Guitar, Electric Guitar, Percussion [Toumba], Tambourine, Maracas, Chorus : Prosper N\'Kouri · Artwork [Conception Graphique] : Antoine Castro · Bass : Aladji Touré · Cavaquinho : Chiquinho Timotéo · Chorus : Liliane Mayordome · Directed By : Michel Carras',
    tracks: [
      { title: "Eseringila", track_number: 1, youtube_url: 'https://www.youtube.com/watch?v=Bk8wdAiiruk' },
      { title: "Labada", track_number: 2, youtube_url: 'https://www.youtube.com/watch?v=6FBdhrwI-4Y' },
      { title: "Ntyango", track_number: 3, youtube_url: 'https://www.youtube.com/watch?v=yBsMkS-Jr1c' },
      { title: "Ezele / Arrête-Toi Un Moment", track_number: 4, youtube_url: 'https://www.youtube.com/watch?v=ZzyTJuOmGnQ' },
      { title: "Nwo Nyoni", track_number: 5, youtube_url: 'https://www.youtube.com/watch?v=W6s1KBUWAZY' },
      { title: "Eswangongo", track_number: 6, youtube_url: 'https://www.youtube.com/watch?v=ScX3GNLeGps' },
      { title: "Mbela", track_number: 7, youtube_url: 'https://www.youtube.com/watch?v=EwRb50hb6Fk' },
      { title: "Chaka", track_number: 8, youtube_url: 'https://www.youtube.com/watch?v=rNi8sw_UgYA' },
      { title: "Aux Dieux De Ce Monde", track_number: 9, youtube_url: 'https://www.youtube.com/watch?v=OsuDk1hPWw0' },
      { title: "Piamidanga (Le Rapporteur)", track_number: 10, youtube_url: 'https://www.youtube.com/watch?v=IKDJDGET4pM' },
      { title: "Kengele", track_number: 11, youtube_url: 'https://www.youtube.com/watch?v=vI4h6Oily1I' },
      { title: "Izingo (Dur-Dur-Dur)", track_number: 12, youtube_url: 'https://www.youtube.com/watch?v=CBq19diUP1o' },
      { title: "Mye We", track_number: 13, youtube_url: 'https://www.youtube.com/watch?v=cK-PpqDt21s' },
      { title: "Ibangani", track_number: 14, youtube_url: 'https://www.youtube.com/watch?v=rbGLfeCzX1I' },
      { title: "Méngo", track_number: 15, youtube_url: 'https://www.youtube.com/watch?v=V5orLtrPDd4' },
    ],
  },
  {
    title: "Ekunda-Sah!",
    year: 2004,
    slug: 'ekunda-sah',
    format: "CD",
    label: "Romepa (83006)",
    genre: "Folk, World, & Country / African",
    description: "24 page Booklet",
    credits: null,
    tracks: [
      { title: "Embarra", track_number: 1, youtube_url: 'https://www.youtube.com/watch?v=DR7ZxbGsqCY' },
      { title: "Imèna", track_number: 2, youtube_url: 'https://www.youtube.com/watch?v=PT-ha1-YgRs' },
      { title: "La pauvreté", track_number: 3, youtube_url: 'https://www.youtube.com/watch?v=qRmJrI3fsmM' },
      { title: "Evangavanga", track_number: 4, youtube_url: 'https://www.youtube.com/watch?v=EG9ik--pE18' },
      { title: "La colombe", track_number: 5, youtube_url: 'https://www.youtube.com/watch?v=8FRHkn_X7CA' },
      { title: "Edunda", track_number: 6, youtube_url: 'https://www.youtube.com/watch?v=UFIOxkaVuVA' },
      { title: "Du bas d'en haut", track_number: 7, youtube_url: 'https://www.youtube.com/watch?v=9a2e5SxykKs' },
      { title: "Assikwee", track_number: 8, youtube_url: 'https://www.youtube.com/watch?v=dEc2jbN3aD4' },
      { title: "Ilombo", track_number: 9, youtube_url: 'https://www.youtube.com/watch?v=0itvwhna7D4' },
      { title: "Movèdi", track_number: 10, youtube_url: 'https://www.youtube.com/watch?v=AgyfiVqaLTo' },
      { title: "Okulé Kulee", track_number: 11, youtube_url: 'https://www.youtube.com/watch?v=DgsF__tbY18' },
      { title: "Mbéléwélee ”", track_number: 12, youtube_url: 'https://www.youtube.com/watch?v=9Be51_qbT0s' },
    ],
  },
  {
    title: "Tous Nos Meaux",
    year: 2005,
    slug: 'tous-nos-meaux',
    format: "CD",
    label: "Lusafrica (462605)",
    genre: "Folk, World, & Country / African",
    description: "Released in cardsleeve.",
    credits: null,
    tracks: [
      { title: "Tous Nos Meaux", track_number: 1, youtube_url: 'https://www.youtube.com/watch?v=MysfalekYO4' },
      { title: "la Chanson De Gorée", track_number: 2, youtube_url: 'https://www.youtube.com/watch?v=UJU3W3ZTtyc' },
    ],
  },
  {
    title: "Gorée",
    year: 2006,
    slug: 'goree',
    format: "CD",
    label: "Lusafrica (462502)",
    genre: "Folk, World, & Country / African",
    description: "Recorded at Studio Md Libreville, Studio ST-Cirq, Grand Yael, Wamboland Besançon, Accès Digital.\r\nMixed and mastered at Studio Accès Digital Rouen.\r\n\r\n℗ 2005 Romega Gabon / Pierre Akendengue\r\n© 2006 Lusafrica",
    credits: 'Artwork : Hartland Villa · Chorus [Female Chorus] : Axelle Bakala · Chorus [Male Chorus] : Augustin Eyenga · Contrabass : Ivan Lantos · Photography By : Youri Lenquette · Producer, Arranged By : Ivan Lantos · Recorded By [Accès Digital] : Thierry Minot · Recorded By [Accès Digital], Mixed By, Mastered By : François Casays',
    tracks: [
      { title: "Gorée", track_number: 1, youtube_url: 'https://www.youtube.com/watch?v=tBJO3PpZC9Q' },
      { title: "Bekelia", track_number: 2, youtube_url: 'https://www.youtube.com/watch?v=UbbJhwzDWPI' },
      { title: "Tous Nos Maux", track_number: 3, youtube_url: 'https://www.youtube.com/watch?v=MysfalekYO4' },
      { title: "Beau Pays Bo", track_number: 4, youtube_url: 'https://www.youtube.com/watch?v=bPNNblctD0c' },
      { title: "Yemba Gorée", track_number: 5, youtube_url: 'https://www.youtube.com/watch?v=RW93FG10Txo' },
      { title: "Lenya Lenya", track_number: 6, youtube_url: 'https://www.youtube.com/watch?v=rS3cpumosyY' },
      { title: "Ya'Nzambe", track_number: 7, youtube_url: 'https://www.youtube.com/watch?v=vE4pn7K8AFo' },
      { title: "Awirondyogo", track_number: 8, youtube_url: 'https://www.youtube.com/watch?v=lK-fMO-T1m4' },
      { title: "De La Forêt", track_number: 9, youtube_url: 'https://www.youtube.com/watch?v=rsUVGQjXaxw' },
      { title: "Imbolwimbolo", track_number: 10, youtube_url: 'https://www.youtube.com/watch?v=v6Hd--56rDo' },
      { title: "Dedede", track_number: 11, youtube_url: 'https://www.youtube.com/watch?v=B68t5l9ZGYw' },
      { title: "La Chanson De Gorée", track_number: 12, youtube_url: 'https://www.youtube.com/watch?v=UJU3W3ZTtyc' },
    ],
  },
  {
    title: "Vérité D'Afrique",
    year: 2008,
    slug: 'verite-d-afrique',
    format: "CD",
    label: "Lusafrica (562252)",
    genre: "Folk, World, & Country / African",
    description: "Recorded at Studios MD-Libreville (Gabon), Saint-Cirq Souillaget, Do Soul (Paris).\n\n℗ 2008 Lusafrica\n© 2008 Lusafrica",
    credits: 'Acoustic Guitar : João Pina "Kako" Alves · Arranged By : Fernando Andrade · Artwork : Hartland Villa · Bass Guitar : José Paris · Bass Guitar, Piano, Keyboards, Sequenced By : Ivan Lantos · Cavaquinho : Paulino Vieira · Chorus [Female Voices] : Axelle Bakala · Chorus [Male Voices], Percussion : Sam Ateba',
    tracks: [
      { title: "Ntyozo Biada", track_number: 1, youtube_url: 'https://www.youtube.com/watch?v=LJPVOtDMdZ4' },
      { title: "Nos Langues De Bois", track_number: 2, youtube_url: 'https://www.youtube.com/watch?v=tOSzwXyjI-o' },
      { title: "Egomé Ewoga", track_number: 3, youtube_url: 'https://www.youtube.com/watch?v=-5fvmk5sgb0' },
      { title: "Tondavowé", track_number: 4, youtube_url: 'https://www.youtube.com/watch?v=5Mi2f5k2rZg' },
      { title: "Vérité D'Afrique", track_number: 5, youtube_url: 'https://www.youtube.com/watch?v=jvmL9SwCMgE' },
      { title: "Aré Kao", track_number: 6, youtube_url: 'https://www.youtube.com/watch?v=ClyfeY7DVzY' },
      { title: "Afrika Obota", track_number: 7, youtube_url: 'https://www.youtube.com/watch?v=dBbVvlmYeg8' },
      { title: "Izimi", track_number: 8, youtube_url: 'https://www.youtube.com/watch?v=5jP7farJh1U' },
      { title: "Oparapara", track_number: 9, youtube_url: 'https://www.youtube.com/watch?v=6gbGnuPCjK4' },
      { title: "Pays Pillé", track_number: 10, youtube_url: 'https://www.youtube.com/watch?v=wZtAXH-17kI' },
      { title: "Dewemori", track_number: 11, youtube_url: 'https://www.youtube.com/watch?v=BVD7gENY5vQ' },
      { title: "Tanguna Gakumuna", track_number: 12, youtube_url: 'https://www.youtube.com/watch?v=B_F0GkjQHh0' },
      { title: "Considérable", track_number: 13, youtube_url: 'https://www.youtube.com/watch?v=0b332fAlZhM' },
      { title: "Oyangayanga", track_number: 14, youtube_url: 'https://www.youtube.com/watch?v=x0jOQw-iT_g' },
    ],
  },
  {
    title: "Destinée",
    year: 2013,
    slug: 'destinee',
    format: "",
    label: "None",
    genre: "Hip Hop",
    description: "",
    credits: 'Producer : Michael Uzowuru',
    tracks: [
      { title: "ADD", track_number: 1, youtube_url: 'https://www.youtube.com/watch?v=B68t5l9ZGYw' },
      { title: "beyond category 91", track_number: 2, youtube_url: 'https://www.youtube.com/watch?v=SbM738tQsH8' },
      { title: "camo hat", track_number: 3, youtube_url: 'https://www.youtube.com/watch?v=m-F_SkKIZYM' },
      { title: "indigo spirit", track_number: 4, youtube_url: 'https://www.youtube.com/watch?v=n2DBatm9pt8' },
      { title: "martian child", track_number: 5, youtube_url: 'https://www.youtube.com/watch?v=rNQ8Nk4SgGs' },
      { title: "moredicai", track_number: 6, youtube_url: 'https://www.youtube.com/watch?v=BVD7gENY5vQ' },
      { title: "royal", track_number: 7, youtube_url: 'https://www.youtube.com/watch?v=N6nXqO7LowM' },
      { title: "sabbatical", track_number: 8, youtube_url: 'https://www.youtube.com/watch?v=72iIgaJbPUY' },
      { title: "somewhere", track_number: 9, youtube_url: 'https://www.youtube.com/watch?v=YgboB542jlY' },
      { title: "synesthesia", track_number: 10, youtube_url: 'https://www.youtube.com/watch?v=L9VmL-3CDXQ' },
      { title: "", track_number: 11, youtube_url: 'https://www.youtube.com/watch?v=rB_qYnQkjIw' },
      { title: "", track_number: 12, youtube_url: 'https://www.youtube.com/watch?v=d9xmMK-uWLA' },
      { title: "", track_number: 13, youtube_url: 'https://www.youtube.com/watch?v=PUQMZAvhacQ' },
      { title: "", track_number: 14, youtube_url: 'https://www.youtube.com/watch?v=PUQMZAvhacQ' },
    ],
  },
  {
    title: "Libérée La Liberté / Mvt Arusha",
    year: 2016,
    slug: 'liberee-la-liberte-mvt-arusha',
    format: "CDr",
    label: "Lusafrica",
    genre: "Folk, World, & Country / African",
    description: "Promo Cdr in cardsleeve. otherwise digital release only issued july 1st 2016.\nhttp://hyperurl.co/l3rqjg\nhttps://www.facebook.com/PCAkendengue/photos/a.362392247195379/794536350647631/?type=3&theater",
    credits: 'Written-By : Pierre Akendengue',
    tracks: [
      { title: "Libérée La Liberté (Radio Edit)", track_number: 1, youtube_url: 'https://www.youtube.com/watch?v=KHhxzJxV-5c' },
      { title: "Mvt Arusha (Radio Edit)", track_number: 2, youtube_url: 'https://www.youtube.com/watch?v=1KF0fg-tH_U' },
      { title: "Libérée La Liberté (Version Originale)", track_number: 3, youtube_url: 'https://www.youtube.com/watch?v=KHhxzJxV-5c' },
      { title: "Mvt Arusha (Version Originale)", track_number: 4, youtube_url: 'https://www.youtube.com/watch?v=1KF0fg-tH_U' },
    ],
  },
  {
    title: "La Couleur De L'Afrique",
    year: 2018,
    slug: 'la-couleur-de-l-afrique',
    format: "CD",
    label: "Romepa",
    genre: "Folk, World, & Country / African",
    description: "",
    credits: null,
    tracks: [
      { title: "La Couleur De L'Afrique", track_number: 1, youtube_url: 'https://www.youtube.com/watch?v=gW54-BoMY-I' },
      { title: "Lettre À Laurent Gbaggbo", track_number: 2, youtube_url: 'https://www.youtube.com/watch?v=oyja69LpFAI' },
      { title: "Oparapara-Para", track_number: 3, youtube_url: 'https://www.youtube.com/watch?v=TrCp-cFcAX8' },
      { title: "Deux-Mocrates", track_number: 4, youtube_url: 'https://www.youtube.com/watch?v=YtzswwSQh-A' },
    ],
  },
];

export async function seed() {
  console.log('🌱 Démarrage du seed Pierre Akendengue...\n');

  const [artist] = await db
    .insert(artists)
    .values({
      name: 'Pierre Akendengue',
      slug: 'pierre-akendengue',
      bio: PIERRE_AKENDENGUE_BIO,
      photo_url: null,
      avatar_url: null,
      born_year: 1942,
    })
    .onConflictDoUpdate({ target: artists.slug, set: { bio: PIERRE_AKENDENGUE_BIO, name: 'Pierre Akendengue' } })
    .returning();

  console.log(`✅ Artiste : ${artist.name} (${artist.id})\n`);

  const existingAlbums = await db
    .select({ slug: albums.slug, image_url: albums.image_url })
    .from(albums)
    .where(eq(albums.artist_id, artist.id));
  const savedImageUrls: Record<string, string | null> = Object.fromEntries(
    existingAlbums.map((a) => [a.slug, a.image_url])
  );

  await db.delete(albums).where(eq(albums.artist_id, artist.id));

  for (const disc of PIERRE_AKENDENGUE_DISCOGRAPHY) {
    const [album] = await db
      .insert(albums)
      .values({
        artist_id: artist.id,
        title: disc.title,
        slug: disc.slug,
        year: disc.year,
        format: disc.format,
        label: disc.label,
        genre: disc.genre,
        description: disc.description,
        credits: disc.credits ?? null,
        image_url: savedImageUrls[disc.slug] ?? null,
      })
      .returning();

    const trackCount = disc.tracks.length;
    console.log(`  📀 ${disc.year} — ${disc.title} [${disc.format}] · ${disc.label}`);

    if (trackCount > 0) {
      await db.insert(tracks).values(
        disc.tracks.map((t) => ({
          album_id: album.id,
          title: t.title,
          track_number: t.track_number,
          duration: null,
          youtube_url: t.youtube_url ?? null,
          lyrics_fr: null,
          lyrics_original: null,
          context: null,
        }))
      );
      console.log(`     └ ${trackCount} titre(s)`);
    }
  }

  console.log('\n🌳 Seed terminé.');
}

if (require.main === module) {
  seed().then(() => process.exit(0)).catch((err) => {
    console.error('Erreur seed :', err);
    process.exit(1);
  });
}
